version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:2.4.2
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
  cmdelasticsearch:
    image: elasticsearch:5
    ports:
      # Set alternative ports to prevent port clash.
      - 10300:9300
      - 10200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  highcharts:
    image: onsdigital/highcharts-export-node
    ports:
      - "9999:8080"
  postgres:
    build: ./postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
  mongodb:
    image: mongo
    ports:
      - 27017:27017
#  neo4j:
#    image: neo4j:3.2.12
#    ports:
#      - 7474:7474
#      - 7687:7687
#    environment:
#      - "NEO4J_AUTH=none"
#      - "NEO4J_dbms_memory_pagecache_size=5G"
#      - "NEO4J_dbms_memory_heap_max__size=5G"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.0.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mathjax:
    image: onsdigital/mathjax-api
    ports:
      - "8888:8080"
  vault:
    image: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "mooquackplop"
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK

  dp-sessions-api:
    image: dp-sessions-api
    build:
      context: repos/dp-sessions-api
      dockerfile: Dockerfile.jj
    environment:
      ZEBEDEE_URL: "http://localhost:8082"
      SERVICE_AUTH_TOKEN: ""
    ports:
      - 24400:24400
#    depends_on:
#      - zebedee

#  zebedee:
#    image: zebedee
#    build:
#      context: repos/zebedee
#      dockerfile: Dockerfile.jj
#    environment:
##    ports:
#    volumes:
#      - type: bind
#        source: ./zebedee-content
#        target: /zebedee-content